const express=require("express"),helmet=require("helmet"),rateLimit=require("express-rate-limit"),path=require("path"),Database=require("better-sqlite3");
const app=express(),PORT=process.env.PORT||3000,db=new Database(process.env.DB_PATH||path.join(__dirname,"internships.db"));
app.disable("x-powered-by"); app.use(helmet()); app.use(express.json({limit:"20kb"}));
app.use("/api/",rateLimit({windowMs:15*60*1000,limit:100,standardHeaders:"draft-7",legacyHeaders:false}));
db.exec(`CREATE TABLE IF NOT EXISTS internships(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,company TEXT NOT NULL,domain TEXT NOT NULL,location TEXT NOT NULL,skills TEXT NOT NULL,description TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
if(!db.prepare("SELECT COUNT(*) c FROM internships").get().c){const q=db.prepare("INSERT INTO internships(title,company,domain,location,skills,description) VALUES(?,?,?,?,?,?)");[["AI/ML Intern","Nova Labs","AI/ML","Bengaluru","Python, ML, SQL","Build beginner-friendly machine learning features."],["Frontend Developer Intern","PixelWorks","Web Development","Remote","HTML, CSS, JavaScript","Create responsive interfaces."],["Data Science Intern","DataBridge","Data Science","Hyderabad","Python, Pandas, SQL","Clean data and build analytics workflows."],["Backend Developer Intern","CloudNest","Web Development","Pune","Node.js, Express, REST","Implement APIs with validation."],["Computer Vision Intern","VisionForge","AI/ML","Chennai","Python, OpenCV, YOLO","Prototype computer vision solutions."],["Data Analyst Intern","InsightHub","Data Science","Remote","Excel, SQL, Power BI","Prepare reports and insights."]].forEach(x=>q.run(...x))}
const clean=(v,n=120)=>typeof v==="string"?v.trim().slice(0,n):"";
app.get("/health",(_,res)=>res.json({status:"ok"}));
app.get("/api/internships",(req,res)=>{const page=Math.max(1,parseInt(req.query.page)||1),limit=Math.min(100,Math.max(1,parseInt(req.query.limit)||10)),s=clean(req.query.search,80),d=clean(req.query.domain,50),w=[],p=[];if(s){w.push("(title LIKE ? OR company LIKE ? OR skills LIKE ?)");const t=`%${s}%`;p.push(t,t,t)}if(d&&d!=="All domains"){w.push("domain = ?");p.push(d)}const c=w.length?`WHERE ${w.join(" AND ")}`:"",total=db.prepare(`SELECT COUNT(*) total FROM internships ${c}`).get(...p).total,rows=db.prepare(`SELECT * FROM internships ${c} ORDER BY id LIMIT ? OFFSET ?`).all(...p,limit,(page-1)*limit);res.json({data:rows,pagination:{page,limit,total,totalPages:Math.max(1,Math.ceil(total/limit))}})});
function validate(b){const name=clean(b.name,80),email=clean(b.email,160),id=Number(b.internshipId),message=clean(b.message,1000),e={};if(!/^[A-Za-z][A-Za-z .'-]{1,79}$/.test(name))e.name="Enter a valid name.";if(!/^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(email))e.email="Enter a valid email.";if(!Number.isInteger(id)||id<1)e.internshipId="Select a valid internship.";if(message.length<10)e.message="Message must contain at least 10 characters.";return{ok:!Object.keys(e).length,e,data:{name,email,id,message}}}
app.post("/api/applications",(req,res)=>{const v=validate(req.body||{});if(!v.ok)return res.status(400).json({error:{code:"VALIDATION_ERROR",message:"Request validation failed.",details:v.e}});if(!db.prepare("SELECT id FROM internships WHERE id=?").get(v.data.id))return res.status(404).json({error:{code:"NOT_FOUND",message:"Internship not found."}});res.status(201).json({data:{message:"Application accepted for review.",applicant:{name:v.data.name,email:v.data.email},internshipId:v.data.id}})});
app.use(express.static(path.join(__dirname,"public"))); app.use((e,_,res,__)=>res.status(500).json({error:{code:"SERVER_ERROR",message:"Internal server error."}}));
if(require.main===module)app.listen(PORT,()=>console.log(`Server running on http://localhost:${PORT}`)); module.exports={app,db};